logging:
  file: logs/frontend-facade.log
  level:
    root: INFO
    com:
      github:
        forinil: TRACE
    org:
      springframework:
        data: DEBUG
        web: DEBUG
spring:
  data:
    gemfire:
      cache:
        log-level: ERROR