spring:
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: "123"
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
      path: /console
      custom:
        enabled: true